wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<title>",views.entry, name="entry"),
    path("search", views.search, name="search"),
    path("create", views.create, name="create"),
    path("wiki/edit/<title>", views.edit, name="edit"),
    path("random", views.random, name="random")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
from markdown2 import markdown
from django.http import HttpResponseRedirect
from django import forms
from . import util
from random import randint


class NewPageForm(forms.Form):
    title = forms.CharField(label='Title', required=True, widget=forms.TextInput(attrs={'placeholder':'Enter Title','class':'col-sm-11', 'style':'left:1rem'}))
    content = forms.CharField(label='Markdown Content', required = True, widget=forms.Textarea(attrs={'placeholder':'Enter markdown content','class':'col-sm-11','style':'top:1rem'}))

class EditPageForm(forms.Form):
    title = forms.CharField(label='Title', required=True, widget=forms.HiddenInput)
    content = forms.CharField(label='Markdown Content', required = True, widget=forms.Textarea(attrs={'placeholder':'Enter markdown content','class':'col-sm-11','style':'top:1rem'}))



def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

# Entry Page
def entry(request, title):
    content_md = util.get_entry(title) # in markdown format

    if content_md is None:
        content_md = "This page does not exist!"

        return render(request, "encyclopedia/error.html", {
            "content": content_md,
            "title": title
        })
        
    
    content_html = markdown(content_md) #convert markdown to html

    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "content": content_html,
    })

# Search
def search(request):
    query = request.GET.get('q', '') # looks for a GET parameter named q and returns an empty string if that parameter wasnt submitted.

    if query in util.list_entries():
        # redirects to the wiki/query page if query is inside the list of entries
        
        return HttpResponseRedirect("wiki/"+query)
    
    else:
        # redirects to a list of entries with titles containing query in its title string
        # e.g. 'py' in 'python'

        possible_entry_list = [] # empty list to store the possible entries that have the query as a substring

        for entry in util.list_entries():
            if entry.lower().startswith(query.lower()): # convert both query substring and entry string to lowercase
                possible_entry_list.append(entry)

        if not possible_entry_list:
            content = "The page \'" + query + "\' does not exist. There were no results matching that query."
            
            return render(request, "encyclopedia/error.html", {
                "content": content,
                "title": query
            })

        else: 
            return render(request, "encyclopedia/index.html", {
                "entries": possible_entry_list
            })

# Create new page
def create(request):
    if request.method == 'POST':
        new_form = NewPageForm(request.POST)
        if not new_form.is_valid():
            return render(request, "encyclopedia/create.html", {
                "form": new_form,
                "message": "Title or content is missing. Please ensure that you provide both Title and Content."
            })
        else:
            title = new_form.cleaned_data["title"]
            content = new_form.cleaned_data["content"]
            
            for name in util.list_entries():
                if title.lower() == name.lower():
                    return render(request, "encyclopedia/create.html", {
                        "form": NewPageForm(),
                        "message": "Page with title: '"+title+"' already exists in Wiki Encyclopedia. Please try again."
                    })
            util.save_entry(title, content)

            return redirect("encyclopedia:entry", title=title)

    return render(request, "encyclopedia/create.html", {
        "form": NewPageForm()
    })


# Edit page
def edit(request, title):
    # get content
    content = util.get_entry(title)
    
    #initialise the edit_form
    edit_form = EditPageForm(initial={'title':title, 'content':content})

    if request.method == 'POST':
        edit_form = EditPageForm(request.POST)
        
        if edit_form.is_valid():
            title = edit_form.cleaned_data["title"]
            content = edit_form.cleaned_data["content"]
            util.save_entry(title, content)

            content_html = markdown(content)

            return render(request, "encyclopedia/entry.html", {
                "title": title,
                "content": content_html
            })
    
    return render(request, "encyclopedia/edit.html", {
        "title": title,
        "form": edit_form
    })

#get random entry page
def random(request):
    
    list_of_entries = util.list_entries()
    random_entry = list_of_entries[randint(0, len(list_of_entries)-1)]

    return redirect('encyclopedia:entry', title=random_entry)

        

wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Page
{% endblock %}

{% block body %}
    <h1>Create a New Page</h1>
    
    {% if message %}
        <h4 class="text-danger"> {{message}} </h4> 
    {% endif %}

    <form action="{% url 'encyclopedia:create' %}" method="POST">
        {% csrf_token %}
        <div>
            {{ form }}
        </div>
        <input type="submit" style="margin-top: 1rem">
    </form>
    

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block body %}
    <h1>Edit Page: {{ title }}</h1>
    
    <form action="{% url 'encyclopedia:edit' title %}" method="POST">
        {% csrf_token %}
        <div>
            {{ form }}
        </div>
        <input type="submit" value="Save" style="margin-top: 1rem">
    </form>
    

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
  
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
	{{ content|safe }}
	<a href="{% url 'encyclopedia:edit' title %}"><input type="submit" value="Edit" name="edit" class="btn btn-success my-3" /></a>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>ERROR</h1>

    <div class="container">
        {{content}}
    </div>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <a href="{% url 'encyclopedia:entry' entry %}"><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>